<a href="https://colab.research.google.com/github/MerwinMaravilla/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Promblem 1
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
print(f'Matrix A:\n {A}')
print()
B = np.array([[89],[89],[95]])
print(f'Matrix B:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n{C}')



Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
[[13.]
 [57.]
 [19.]]


In [4]:
#Promblem 2
import numpy as np
A = np.array([[3,-1,1],[9,3,3],[-12,4,-4]])
B = np.array ([[5],[15],[-20]]) 
roots = np.linalg.inv(A),(B)
print(roots)
#What property of matrix that can not be solved by any method in solving Linear Equations?
Singular Matrix

LinAlgError: ignored

In [2]:
#Promblem 3
import numpy as np
from scipy.linalg import solve
#from nump.linalg import eig
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are:",v)
#w+v.round()
#print(X)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are: [-1.  3.  2.]
The right eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.24992575e-15]
 [-3.01511345e-01 -2.31918026e-15  7.07106781e-01]]
