<a href="https://colab.research.google.com/github/MerwinMaravilla/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#question1
import numpy as np
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[0,1,2,3,4]])
#print square matrix 
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  1  2  3  4]]


In [4]:
#question2
import numpy as np 
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [15]:
#question3
import numpy as np

A =np.array([[6,1,6],[1,5,2],[6,2,7]])
print(A)
print("/n")
#prints transpose matrix

print(np.transpose(A))


[[6 1 6]
 [1 5 2]
 [6 2 7]]
/n
[[6 1 6]
 [1 5 2]
 [6 2 7]]


In [1]:
#question4
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
B = (np.linalg.inv(A))
# print inverse matrix
print(B)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [2]:
#question5
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
#printd determinant matrix
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


In [19]:
#question6
import numpy as np
c= np.array([[5,4,1],[10,9,4],[10,13,15]])
inv_c = np.linalg.inv(c)
print(c)
print()
print(inv_c)

d = np.array([[3,4],[8,8],[19,2]])

x=np.dot(inv_c, d)
print("roots =")
print(x)

z=np.dot(c,x) #checking
print("checking")
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
roots =
[[ 4.00000000e-01 -2.00000000e+00]
 [-1.66533454e-15  4.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00]]
checking
[[ 3.  4.]
 [ 8.  8.]
 [19.  2.]]
