<a href="https://colab.research.google.com/github/MerwinMaravilla/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Promblem 1

In [8]:

import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2],[9,0],[-1,2]])
print(W*Y)

[[ 1 -6]
 [18  0]
 [-3  2]]


In [2]:

import numpy as np
Z = np.array([[0,1],[2,3]])

print(Z+Z)

[[0 2]
 [4 6]]


In [11]:

X = np.array([3,2,1,-1,2,3,2-1,1])
S = 3*x
print(S)

[ 9  6  3 -3  6  9  3  3]


Promblem 2

In [43]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

D = np.dot(Y,W)

print(D*D)

#Statement is not true

[[25 49]
 [16 16]]


In [54]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,9],[0,-1,2]])
X = np.array([[3,2],[1-1],[2,3],[2-1],[1]])

D = np.dot(W,Y)

print(np.subtract(D,X))

#Statement is true


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


ValueError: ignored

In [52]:
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])

D = np.dot(Y,A)
E = Z*Z

#Statement is not true

print(np.subtract(D,E))

[[ 5 -8]
 [ 0 -5]]
