<a href="https://colab.research.google.com/github/MerwinMaravilla/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix C

In [8]:
# import the important module in python
import numpy as np
         
# make matrix with numpy
A = np.matrix('[1, 5; 6, 4]')
B = np.matrix('[2, 4; 7, 4]')
         
# applying matrix.diagonal() method
C = A,B.diagonal()
   
print(C)

(matrix([[1, 5],
        [6, 4]]), matrix([[2, 4]]))


Question 2

In [11]:
A = np.matrix('[1, 5; 6, 4]')
B = np.matrix('[2, 4; 7, 4]')
C = 2*A,B
print(C)

(matrix([[ 2, 10],
        [12,  8]]), matrix([[2, 4],
        [7, 4]]))


Question 3

In [4]:
#initialize arrays
A = np.array([2,7,4])
B = np.array([3,9,8])

#compute cross product
output = np.cross(A,B)
print(output)

[20 -4 -3]
